{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hub.serviceAccountName" . }}
  labels:
    {{- include "hub.labels" . | nindent 8 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
